Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  #config.disksize.size = "15GB"
  
  config.vm.hostname = "vubnt"
  config.vm.network "public_network", bridge: "Broadcom NetLink (TM) Gigabit Ethernet #2"
  config.vm.box_check_update = false

  if Vagrant.has_plugin?("vagrant-vbguest") then
    #config.vbguest.auto_update = false
    config.vbguest.no_install  = true
  end

  # Customize the amount of memory and cpu on the VM:
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
  end
    
  # minikube installation    
  config.vm.provision "shell", path: "install.sh"
  
  # some user configs
  config.vm.provision "file", source: "./gitconfig", destination: "/home/vagrant/.gitconfig"
  config.vm.provision "file", source: "./vimrc", destination: "/home/vagrant/.vimrc"

end
