Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  
  
  if Vagrant.has_plugin?("vagrant-vbguest") then
    #config.vbguest.auto_update = false
    config.vbguest.no_install  = true
  end
  
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.cpus = 2
    #vb.customize ["storagectl", :id, "--name", "SCSI", "--remove"]
    #vb.customize ["storagectl", :id, "--name", "SATA Controller", "--add", "sata"]
  end
      
  #config.vm.provision "shell", path: "script.sh"
  
  config.vm.provision "shell", inline: "apt-get update; apt-get install -y python2.7 python-pip virtualenv"

end
